# Generated by Django 2.2.5 on 2019-12-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191223_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='langauge',
        ),
    ]
