# Generated by Django 2.2.5 on 2020-03-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200313_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=0, help_text='How many people will be staying?'),
        ),
    ]
