# Generated by Django 2.2.5 on 2020-04-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_conversation'),
        ('conversations', '0003_auto_20200410_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='reservations',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='reservations.Reservation'),
        ),
    ]
