# Generated by Django 2.2.5 on 2020-04-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='reservations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='reservations.Reservation'),
        ),
    ]
