# Generated by Django 2.2.5 on 2020-04-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20200410_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='reservations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='reservations.Reservation'),
        ),
    ]
