# Generated by Django 2.2.5 on 2020-04-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_auto_20200411_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='reservations',
        ),
    ]
