# Generated by Django 2.2.5 on 2020-04-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200410_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='conversation',
        ),
    ]
