# Generated by Django 2.2.5 on 2020-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200310_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
